### ISSUE TITLE
showing player tag

### ISSUE THREAD

**Issue by Sensetivity** [zephir-lang/zephir-docs-app#32]
On tutorial page we have a video player.  
https://docs.zephir-lang.com/0.12/en/tutorial

For English language it is fine but for other languages it shows tag "<iframe src="//player.vimeo.com/video/84180223" width="500" height="313" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen mark="crwd-mark"></iframe>".

It looks like some encoding/escaping.

**Comment by Arhell** [comment]
@Sensetivity thank you for this issue, resolve.
